Use check-sparql to run queries driven by manifests and check results are correct.  Enable this in check-local

diff --git a/tests/sparql/part1/Makefile.am b/tests/sparql/part1/Makefile.am
--- a/tests/sparql/part1/Makefile.am
+++ b/tests/sparql/part1/Makefile.am
@@ -26,7 +26,7 @@ dawg-data-01.n3
 SPARQL_TEST_FILES= \
 dawg-query-001 dawg-query-002 dawg-query-003
 
-EXPECTED_SPARQL_TEST_FAILURES=
+EXPECTED_SPARQL_CORRECT_FAILURES_COUNT=3
 
 SPARQL_RESULT_FILES= \
 dawg-result-001.n3 dawg-result-002.n3 dawg-result-003.n3
@@ -47,7 +47,8 @@ $(top_builddir)/sparql_parser_test:
 	@(cd $(top_builddir) ; $(MAKE) sparql_parser_test)
 
 
-check-local: check-sparql-lexer check-sparql-parser
+check-local: check-sparql-lexer check-sparql-parser \
+check-sparql-works check-sparql-correct
 
 check-sparql-lexer: $(top_builddir)/sparql_lexer_test
 	@set +e; result=0; \
@@ -78,14 +79,6 @@ check-sparql-parser: $(top_builddir)/sparql_parser_test
 	    $(ECHO) ok; \
 	  fi; \
 	done; \
-	if test $$result = 1 ; then \
-	  echo "Expecting test failures: $(EXPECTED_SPARQL_TEST_FAILURES)"; \
-	  if test "X$$fails" = "X $(EXPECTED_SPARQL_TEST_FAILURES)" ; then \
-	    echo "OK: Ignoring expected test failures"; result=0; \
-          else \
-	    echo "FAILED: failures $$fails does not match expected"; result=1; \
-          fi; \
-	fi; \
 	set -e; exit $$result
 
 check-sparql-works: $(top_builddir)/roqet
@@ -93,7 +86,7 @@ check-sparql-works: $(top_builddir)/roqet
 	$(ECHO) "Testing SPARQL"; \
 	for test in $(SPARQL_TEST_FILES); do \
 	  $(ECHO) $(ECHO_N) "Checking $$test $(ECHO_C)"; \
-	  $(top_builddir)/roqet -i sparql $(srcdir)/$$test >/dev/null 2>&1; \
+	  $(top_builddir)/roqet -i sparql -s dawg-data-01.n3 $(srcdir)/$$test >/dev/null 2>&1; \
 	  status=$$?; \
 	  if test $$status != 0 -a $$status != 2 ; then \
 	    $(ECHO) FAILED returned status $$status; result=1; \
@@ -102,4 +95,19 @@ check-sparql-works: $(top_builddir)/roqet
 	    $(ECHO) ok; \
 	  fi; \
 	done; \
+	set -e; exit $$result
+
+check-sparql-correct: $(top_builddir)/roqet $(srcdir)/../check-sparql
+	@set +e; \
+	TOP_SRCDIR=$(top_srcdir) TOP_BUILDDIR=$(top_builddir) \
+	  perl $(srcdir)/../check-sparql; \
+	result=$$?; \
+	if test $$result != 0 ; then \
+	  echo "Expecting test failures: $(EXPECTED_SPARQL_CORRECT_FAILURES)"; \
+	  if test $$result = $(EXPECTED_SPARQL_CORRECT_FAILURES_COUNT) ; then \
+	    echo "OK: Ignoring expected test failures"; result=0; \
+          else \
+	    echo "FAILED: $$result failures does not match expected $(EXPECTED_SPARQL_CORRECT_FAILURES_COUNT)"; result=1; \
+          fi; \
+	fi; \
 	set -e; exit $$result
